const ActionTypesBooking = {
  REQ_GET_ALL_LIST_BOOKING: "REQ_GET_ALL_LIST_BOOKING",
  RES_GET_ALL_LIST_BOOKING: "RES_GET_ALL_LIST_BOOKING",
  REQ_GET_ONE_BOOKING: "REQ_GET_ONE_BOOKING",
  RES_GET_ONE_BOOKING: "RES_GET_ONE_BOOKING",
  REQ_GET_ALL_FACILITIES_SUPPORT: "REQ_GET_ALL_FACILITIES_SUPPORT",
  RES_GET_ALL_FACILITIES_SUPPORT: "RES_GET_ALL_FACILITIES_SUPPORT",
  REQ_GET_OTHER_ROOMS: "REQ_GET_OTHER_ROOMS",
  RES_GET_OTHER_ROOMS: "RES_GET_OTHER_ROOMS",
  REQ_GET_COUPONS: "REQ_GET_COUPONS",
  RES_GET_COUPONS: "RES_GET_COUPONS",
}

export default ActionTypesBooking
