const ActionTypes = {
  REQ_GET_HOTELS: "REQ_GET_HOTELS",
  GET_HOTELS_RESPONSE: "GET_HOTELS_RESPONSE",
  UPDATE_HOTELS: "UPDATE_HOTELS",
  UPDATE_HOTELS_RESPONSE: "UPDATE_HOTELS_RESPONSE",
  REQ_GET_HOTELS_PAGINATION: "REQ_GET_HOTELS_PAGINATION",
  ADD_HOTELS: "ADD_HOTELS",
  ADD_HOTELS_RESPONSE: "ADD_HOTELS_RESPONSE",
  DEL_HOTELS: "DEL_HOTELS",
  DEL_HOTELS_RESPONSE: "DEL_HOTELS_RESPONSE",
}

export default ActionTypes
