const ActionTypes = {
  REQ_GET_HOTELS: "REQ_GET_HOTELS",
  GET_HOTELS_RESPONSE: "GET_HOTELS_RESPONSE",
  REQ_GET_HOTELS_BY_ID: "REQ_GET_HOTELS_BY_ID",
  GET_HOTELS_RESPONSE_BY_ID: "GET_HOTELS_RESPONSE_BY_ID",
  REQ_GET_HOTELS_BY_NAME: "REQ_GET_HOTELS_BY_NAME",
  GET_HOTELS_RESPONSE_BY_NAME: "GET_HOTELS_RESPONSE_BY_NAME",
  UPDATE_HOTELS: "UPDATE_HOTELS",
  UPDATE_HOTELS_RESPONSE: "UPDATE_HOTELS_RESPONSE",
  REQ_GET_HOTELS_PAGINATION: "REQ_GET_HOTELS_PAGINATION",
  ADD_HOTELS: "ADD_HOTELS",
  ADD_HOTELS_RESPONSE: "ADD_HOTELS_RESPONSE",
  DEL_HOTELS: "DEL_HOTELS",
  DEL_HOTELS_RESPONSE: "DEL_HOTELS_RESPONSE",

  REQ_GET_FACI: "REQ_GET_FACI",
  GET_FACI_RESPONSE: "GET_FACI_RESPONSE",
  REQ_GET_FACI_BY_NAME: "REQ_GET_FACI_BY_NAME",
  GET_FACI_BY_NAME_RESPONSE: "GET_FACI_BY_NAME_RESPONSE",
  ADD_FACI: "ADD_FACI",
  ADD_FACI_RESPONSE: "ADD_FACI_RESPONSE",
  UPDATE_FACI: "UPDATE_FACI",
  UPDATE_FACI_RESPONSE: "UPDATE_FACI_RESPONSE",

  ADD_FACI_PHOTOS: "ADD_FACI_PHOTOS",
  ADD_FACI_PHOTOS_RESPONSE: "ADD_FACI_PHOTOS_RESPONSE",

  REQ_GET_FACI_HISTORY: "REQ_GET_FACI_HISTORY",
  GET_FACI_HISTORY_RESPONSE: "GET_FACI_HISTORY_RESPONSE",
  REQ_GET_FACI_HISTORY_BY_ORDER: "REQ_GET_FACI_HISTORY_BY_ORDER",
  GET_FACI_HISTORY_BY_ORDER_RESPONSE: "GET_FACI_HISTORY_BY_ORDER_RESPONSE",

  REQ_GET_ADDRESS: "REQ_GET_ADDRESS",
  GET_ADDRESS_RESPONSE: "GET_ADDRESS_RESPONSE",
  REQ_GET_ADDRES_BY_ID: "REQ_GET_ADDRES_BY_ID",
  GET_ADDRES_BY_ID_RESPONSE: "GET_ADDRES_BY_ID_RESPONSE",
}

export default ActionTypes
