const ActionTypes ={
UPDATE_RESTOMENU: 'UPDATE_RESTOMENU',
UPDATE_RESTOMENU_RESPONSE: 'UPDATE_RESTOMENU_RESPONSE',
GET_RESTOMENU: 'GET_RESTOMENU',
GET_RESTOMENU_RESPONSE: 'GET_RESTOMENU_RESPONSE',

GET_RESTO: 'GET_RESTO',
GET_RESTO_RESPONSE: 'GET_RESTO_RESPONSE',

ADD_RESTOMENU: 'ADD_RESTOMENU',
ADD_RESTOMENU_RESPONSE: 'ADD_RESTOMENU_RESPONSE',
DEL_RESTOMENU: 'DEL_RESTOMENU',
DEL_RESTOMENU_RESPONSE: 'DEL_RESTOMENU_RESPONSE',
};
export default ActionTypes;