const ActionTypes = {

    //VENDOR
    REQ_GET_VENDOR: 'REQ_GET_VENDOR',
    GET_VENDOR_RESPONSE: 'GET_VENDOR_RESPONSE',
    REQ_GET_PRODUCT: 'REQ_GET_PRODUCT',
    GET_PRODUCT_RESPONSE: 'GET_PRODUCT_RESPONSE',
    ADD_VENDOR: 'ADD_VENDOR',
    ADD_VENDOR_RESPONSE: 'ADD_VENDOR_RESPONSE',
    DEL_VENDOR: 'DEL_VENDOR',
    DEL_VENDOR_RESPONSE: 'DEL_VENDOR_RESPONSE',
    UPDATE_VENDOR: 'UPDATE_VENDOR',
    UPDATE_VENDOR_RESPONSE: 'UPDATE_VENDOR_RESPONSE',
    SEARCH_VENDOR: 'SEARCH_VENDOR',
    SEARCH_VENDOR_RESPONSE: 'SEARCH_VENDOR_RESPONSE',

    REQ_GET_PRODUCTID: 'REQ_GET_PRODUCTID',
    GET_PRODUCTID_RESPONSE: 'GET_PRODUCTID_RESPONSE',

    //STOCKS
    REQ_GET_STOCK: "REQ_GET_STOCK",
    GET_STOCK_RESPONSE: 'GET_STOCK_RESPONSE',
    ADD_STOCK: 'ADD_STOCK',
    ADD_STOCK_RESPONSE: 'ADD_STOCK_RESPONSE',
    DEL_STOCK: 'DEL_STOCK',
    DEL_STOCK_RESPONSE: 'DEL_STOCK_RESPONSE',
    UPDATE_STOCK: 'UPDATE_STOCK',
    UPDATE_STOCK_RESPONSE: 'UPDATE_STOCK_RESPONSE',
    FIND_STOCK: 'FIND_STOCK',
    FIND_STOCK_RESPONSE: 'FIND_STOCK_RESPONSE',

    //LISTORDER
    REQ_GET_LISTORDER: "REQ_GET_LISTORDER",
    REQ_GET_LISTORDER_RESPONSE: "REQ_GET_LISTORDER_RESPONSE",
    UPDATE_LISTORDER: 'UPDATE_LISTORDER',
    UPDATE_LISTORDER_RESPONSE: 'UPDATE_LISTORDER_RESPONSE',
    DEL_LISTORDER: 'DEL_LISTORDER',
    DEL_LISTORDER_RESPONSE: 'DEL_LISTORDER_RESPONSE',
    FIND_LISTORDER:'FIND_LISTORDER',
    FIND_LISTORDER_RESPONSE:'FIND_LISTORDER_RESPONSE',
    DEL_LIST_DETAIL: 'DEL_LIST_DETAIL',
    DEL_LIST_DETAIL_RESPONSE: 'DEL_LIST_DETAIL_RESPONSE',

    //VENDOR PRODUCT
    ADD_VEPRO: "ADD_VEPRO",
    ADD_VEPRO_RESPONSE: "ADD_VEPRO_RESPONSE",
    DEL_VEPRO: "DEL_VEPRO",
    DEL_VEPRO_RESPONSE: "DEL_VEPRO_RESPONSE",
    UPDATE_VEPRO: "UPDATE_VEPRO",
    UPDATE_VEPRO_RESPONSE: "UPDATE_VEPRO_RESPONSE",

    //PURCHASE ORDER DETAIL
    ADD_PODE: "ADD_PODE",
    ADD_PODE_RESPONSE: "ADD_PODE_RESPONSE",
    UPDATE_PODE: "UPDATE_PODE",
    UPDATE_PODE_RESPONSE: "UPDATE_PODE",

    //STOCK DETAIL
    ADD_STOD: 'ADD_STOD',
    ADD_STOD_RESPONSE: 'ADD_STOD_RESPONSE',
    UPDATE_STOD: 'UPDATE_STOD',
    UPDATE_STOD_RESPONSE: 'UPDATE_STOD_RESPONSE',

    //PURCHASE ORDER HEADER
    ADD_POHE: 'ADD_POHE',
    ADD_POHE_RESPONSE: 'ADD_POHE_RESPONSE',

    //STOCK PHOTOS
    ADD_PHOTOS: 'ADD_PHOTOS',
    ADD_PHOTOS_RESPONSE: 'ADD_PHOTOS_RESPONSE',
    GET_ALL_PHOTOS: 'GET_ALL_PHOTOS',
    GET_ALL_PHOTOS_RESPONSE: 'GET_ALL_PHOTOS_RESPONSE',
}
export default ActionTypes