const ActionTypes = {

    //VENDOR
    REQ_GET_VENDOR: 'REQ_GET_VENDOR',
    GET_VENDOR_RESPONSE: 'GET_VENDOR_RESPONSE',
    REQ_GET_PRODUCT: 'REQ_GET_PRODUCT',
    GET_PRODUCT_RESPONSE: 'GET_PRODUCT_RESPONSE',
    ADD_VENDOR: 'ADD_VENDOR',
    ADD_VENDOR_RESPONSE: 'ADD_VENDOR_RESPONSE',
    DEL_VENDOR: 'DEL_VENDOR',
    DEL_VENDOR_RESPONSE: 'DEL_VENDOR_RESPONSE',
    UPDATE_VENDOR: 'UPDATE_VENDOR',
    UPDATE_VENDOR_RESPONSE: 'UPDATE_VENDOR_RESPONSE',
    SEARCH_VENDOR: 'SEARCH_VENDOR',
    SEARCH_VENDOR_RESPONSE: 'SEARCH_VENDOR_RESPONSE',

    //STOCKS
    REQ_GET_STOCK: "REQ_GET_STOCK",
    GET_STOCK_RESPONSE: 'GET_STOCK_RESPONSE',

    //LISTORDER
    REQ_GET_LISTORDER: "REQ_GET_LISTORDER",
    REQ_GET_LISTORDER_RESPONSE: "REQ_GET_LISTORDER_RESPONSE",
}
export default ActionTypes