const ActionTypesUsers = {
  REQ_GET_LOGIN: "REQ_GET_LOGIN",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  REQ_LOGOUT: "REQ_LOGOUT",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  REQ_REGISTER: "REQ_REGISTER",
  REGISTER_FAILED: "REGISTER_FAILED",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REQ_LOGIN_GUEST: "REQ_LOGIN_GUEST",
  REQ_REGISTER_GUEST: "REQ_REGISTER_GUEST",

  GET_USERS: "GET_USERS",
  GET_USERS_RESPONSE: "GET_USERS_RESPONSE",

  GET_BONUS_POINT: "GET_BONUS",
  GET_BONUS_POINT_RESPONSE: "GET_BONUS_POINT_RESPONSE",

  GET_HISTORY_MEMBER: "GET_HISTORY_MEMBER",
  GET_HISTORY_MEMBER_RESPONSE: "GET_HISTORY_MEMBER_RESPONSE",
  UPDATE_GENERAL_MEMBER: "UPDATE_GENERAL_MEMBER",
  UPDATE_GENERAL_MEMBER_RESPONSE: "UPDATE_GENERAL_MEMBER_RESPONSE",

  UPDATE_PASSWORD: "UPDATE_PASSWORD",
  UPDATE_PASSWORD_RESPONSE: "UPDATE_PASSWORD_RESPONSE",

  UPDATE_PASSWORD_SUCCESS: "UPDATE_PASSWORD_SUCCESS",
  UPDATE_PASSWORD_FAILED: "UPDATE_PASSWORD_FAILED",
}

export default ActionTypesUsers
