const ActionTypes = {
    REQ_GET_PAGINATION: "REQ_GET_PAGINATION",
    REQ_GET_LOGIN: "REQ_GET_LOGIN",
    LOGIN_FAILED: "LOGIN_FAILED",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    REG_USER: "REG_USER",
    REG_USER_RESPONSE: "REG_USER_RESPONSE",
    UPDATE_USER: "UPDATE_USER",
    UPDATE_USER_RESPONSE: "UPDATE_USER_RESPONSE",
    REQ_GET_USER: "REQ_GET_USER",
    GET_USER: "GET_USER",
    GET_USER_RESPONSE: "GET_USER_RESPONSE",
    ADD_USER: "ADD_USER",
    ADD_USER_RESPONSE: "ADD_USER_RESPONSE",
    DEL_USER: "DEL_USER",
    DEL_USER_RESPONSE: "DEL_USER_RESPONSE",
  
    GET_PRODUCT: "GET_PRODUCT",
    GET_PRODUCT_RESPONSE: "GET_PRODUCT_RESPONSE",
    ADD_PRODUCT: "ADD_PRODUCT",
    ADD_PRODUCT_RESPONSE: "ADD_PRODUCT_RESPONSE",
    DEL_PRODUCT: "DEL_PRODUCT",
    DEL_PRODUCT_RESPONSE: "DEL_PRODUCT_RESPONSE",
    UPDATE_PRODUCT: "UPDATE_PRODUCT",
    UPDATE_PRODUCT_RESPONSE: "UPDATE_PRODUCT_RESPONSE",
  };
  export default ActionTypes;
  