const ActionTypes = {
  GET_DEPARTMENT_RESPONSE: "GET_DEPARTMENT_RESPONSE",
  GET_DEPARTMENT: "GET_DEPARTMENT",
  CREATE_DEPARTMENT: "CREATE_DEPARTMENT",
  CREATE_DEPARTMENT_RESPONSE: "CREATE_DEPARTMENT_RESPONSE",
  DELETE_DEPARTMENT: "DELETE_DEPARTMENT",
  DELETE_DEPARTMENT_RESPONSE: "DELETE_DEPARTMENT_RESPONSE",
  UPDATE_DEPARTEMENT: "UPDATE_DEPARTEMENT",
  UPDATE_DEPARTEMENT_RESPONSE: "UPDATE_DEPARTEMENT_RESPONSE",

  GET_EMPLOYEE: "GET_EMPLOYEE",
  GET_EMPLOYEE_RESPONSE: "GET_EMPLOYEE_RESPONSE",

  CREATE_EMPLOYEE: "CREATE_EMPLOYEE",
  CREATE_EMPLOYEE_RESPONSE: "CREATE_EMPLOYEE_RESPONSE",

  GET_EMPLOYEE_FOR_UPDATE: "GET_EMPLOYEE_FOR_UPDATE",
  GET_EMPLOYEE_FOR_UPDATE_RESPONSE: "GET_EMPLOYEE_FOR_UPDATE_RESPONSE",

  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
  UPDATE_EMPLOYEE_RESPONSE: "UPDATE_EMPLOYEE_RESPONSE",

  GET_JOB_ROLE_OPTION: "GET_JOB_ROLE_OPTION",
  GET_JOB_ROLE_OPTION_RESPONSE: "GET_JOB_ROLE_OPTION_RESPONSE",

  GET_DEPARTMENT_OPTION: "GET_DEPARTMENT_OPTION",
  GET_DEPARTMENT_OPTION_RESPONSE: "GET_DEPARTMENT_OPTION_RESPONSE",

  GET_USERS_FOR_SEARCH_OPTION_EMPLOYEE: "GET_USERS_FOR_SEARCH_OPTION_EMPLOYEE",
  GET_USERS_FOR_SEARCH_OPTION_EMPLOYEE_RESPONSE:
    "GET_USERS_FOR_SEARCH_OPTION_EMPLOYEE_RESPONSE",

  GET_USERS_FOR_PPROFILES: "GET_USERS_FOR_PPROFILES",
  GET_USERS_FOR_PPROFILES_RESPONSE: "GET_USERS_FOR_PPROFILES_RESPONSE",

  GET_SHIFT: "GET_SHIFT",
  GET_SHIFT_RESPONSE: "GET_SHIFT_RESPONSE",

  GET_SHIFT_BY_ID: "GET_SHIFT_BY_ID",
  GET_SHIFT_BY_ID_RESPONSE: "GET_SHIFT_BY_ID_RESPONSE",
}
export default ActionTypes
