const ActionTypePayment ={
    GET_BANK:"GET_BANK",
    GET_BANK_RESPONSE:"GET_BANK_RESPONSE",
    CREATE_BANK: "CREATE_BANK",
    CREATE_BANK_RESPONSE: "CREATE_BANK_RESPONSE",
    UPDATE_BANK: "UPDATE_BANK",
    UPDATE_BANK_RESPONSE: "UPDATE_BANK_RESPONSE",
    DELETE_BANK:'DELETE_BANK',
    DELETE_BANK_RESPONSE:'DELETE_BANK_RESPONSE',

    GET_FINTECH:"GET_FINTECH",
    GET_FINTECH_RESPONSE:"GET_FINTECH_RESPONSE",
    CREATE_FINTECH:"CREATE_FINTECH",
    CREATE_FINTECH_RESPONSE:"CREATE_FINTECH_RESPONSE",
    UPDATE_FINTECH:"UPDATE_FINTECH",
    UPDATE_FINTECH_RESPONSE:"UPDATE_FINTECH_RESPONSE",
    DELETE_FINTECH:"DELETE_FINTECH",
    DELETE_FINTECH_RESPONSE:"DELETE_FINTECH_RESPONSE",

    GET_USER_ACCOUNTS:"GET_USER_ACCOUNTS",
    GET_USER_ACCOUNTS_RESPONSE:"GET_USER_ACCOUNTS_RESPONSE",
    CREATE_USER_ACCOUNTS:"CREATE_USER_ACCOUNTS",
    CREATE_USER_ACCOUNTS_RESPONSE:" CREATE_USER_ACCOUNTS_RESPONSE",
    UPDATE_USER_ACCOUNTS:"UPDATE_USER_ACCOUNTS",
    UPDATE_USER_ACCOUNTS_RESPONSE:" UPDATE_USER_ACCOUNTS_RESPONSE",
    DELETE_USER_ACCOUNTS:"DELETE_USER_ACCOUNTS",
    DELETE_USER_ACCOUNTS_RESPONSE:" DELETE_USER_ACCOUNTS_RESPONSE",
    GET_ACCOUNTS_FINTECH:"GET_ACCOUNTS_FINTECH",
    GET_ACCOUNTS_FINTECH_RESPONSE:"GET_ACCOUNTS_FINTECH_RESPONSE",


    GET_TRANSACTION:"GET_TRANSACTION",
    GET_TRANSACTION_RESPONSE:"GET_TRANSACTION_RESPONSE",
    GET_TRANSACTION_TOPUP:"GET_TRANSACTION_TOPUP",
    GET_TRANSACTION_TOPUP_RESPONSE:"GET_TRANSACTION_TOPUP_RESPONSE",
    CREATE_TRANSACTION_TOPUP:"CREATE_TRANSACTION_TOPUP",
    CREATE_TRANSACTION_TOPUP_RESPONSE:"CREATE_TRANSACTION_TOPUP_RESPONSE"
}

export default ActionTypePayment;