const ActionTypePayment ={
    GET_BANK:"GET_BANK",
    GET_BANK_RESPONSE:"GET_BANK_RESPONSE",
    GET_FINTECH:"GET_FINTECH",
    GET_FINTECH_RESPONSE:"GET_FINTECH_RESPONSE",
    GET_USER_ACCOUNTS:"GET_USER_ACCOUNTS",
    GET_USER_ACCOUNTS_RESPONSE:"GET_USER_ACCOUNTS_RESPONSE",
    GET_TRANSACTION:"GET_TRANSACTION",
    GET_TRANSACTION_RESPONSE:"GET_TRANSACTION_RESPONSE"
}

export default ActionTypePayment;